import ProductCard from '@/app/components/catalogo/ProductCard'
import React from 'react'

export const metadata = {
    title: "Kivara - Catalogo",
    description: "Generated by create next app",
};

const Catalogo = () => {
    return (
        <section className='flex gap-5 flex-wrap p-5 mx-5 items-center justify-center'>
            <ProductCard />
            <ProductCard />
            <ProductCard />
            <ProductCard />
            <ProductCard />
            <ProductCard />
            <ProductCard />   
        </section>
    )
}

export default Catalogo