import ProductList from '@/app/components/catalogo/ProductList';
import React from 'react'

export const metadata = {
    title: "Kivara - Catalogo",
    description: "Generated by create next app",
};

export default function Catalogo() {
    return (
        <section className='flex gap-5 flex-wrap p-5 mx-5 items-center justify-center'>
            <ProductList />
            {/* <ProductCard />
            <ProductCard />
            <ProductCard />
            <ProductCard />
            <ProductCard />
            <ProductCard />
            <ProductCard />    */}
        </section>
    )
}
