import React from 'react'


export const metadata = {
  title: "Kivara - Admin",
  description: "Generated by create next app",
};

const Admin = () => {
  return (
    <div>Admin</div>
  )
}

export default Admin