import { Inter } from "next/font/google";
import "./globals.css";
import Navbar from "./components/ui/navbar";
import Footer from "./components/shared/footer";
import ScrollToTop from "./components/shared/scrollToTop";

const inter = Inter({ subsets: ["latin"] });

export const metadata = {
  title: "Kivara - Layout",
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <body className={inter.className}>
        <ScrollToTop />
        <Navbar />
        {children}
        <Footer />
      </body>
    </html>
  );
}
