import React from 'react'

export const metadata = {
  title: "Kivara - Admin",
  description: "Generated by create next app",
};

export default function Admin ()  {
  return (
    <main>
      Admin
    </main>
  )
}
